-- MySQL Script generated by MySQL Workbench
-- Sat Nov  6 18:49:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asesorapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asesorapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asesorapp` DEFAULT CHARACTER SET utf8 ;
USE `asesorapp` ;

-- -----------------------------------------------------
-- Table `asesorapp`.`tipoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorapp`.`tipoCuenta` (
  `tipo` INT NOT NULL,
  `cuenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorapp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorapp`.`usuario` (
  `matricula` INT NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `tipoCuenta_tipo` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) ,
  INDEX `fk_usuario_tipoCuenta1_idx` (`tipoCuenta_tipo` ASC) ,
  CONSTRAINT `fk_usuario_tipoCuenta1`
    FOREIGN KEY (`tipoCuenta_tipo`)
    REFERENCES `asesorapp`.`tipoCuenta` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorapp`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorapp`.`estado` (
  `noEstado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`noEstado`),
  UNIQUE INDEX `noEstado_UNIQUE` (`noEstado` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorapp`.`asesoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorapp`.`asesoria` (
  `idasesoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `estado_noEstado` INT NOT NULL,
  `usuario_matricula` INT NOT NULL,
  PRIMARY KEY (`idasesoria`),
  INDEX `fk_asesoria_estado_idx` (`estado_noEstado` ASC) ,
  INDEX `fk_asesoria_usuario1_idx` (`usuario_matricula` ASC) ,
  CONSTRAINT `fk_asesoria_estado`
    FOREIGN KEY (`estado_noEstado`)
    REFERENCES `asesorapp`.`estado` (`noEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesoria_usuario1`
    FOREIGN KEY (`usuario_matricula`)
    REFERENCES `asesorapp`.`usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorapp`.`peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorapp`.`peticion` (
  `idpeticion` INT NOT NULL,
  `usuario_matricula` INT NOT NULL,
  `estado_noEstado` INT NOT NULL,
  `asesoria_idasesoria` INT NOT NULL,
  PRIMARY KEY (`idpeticion`),
  INDEX `fk_peticion_usuario1_idx` (`usuario_matricula` ASC) ,
  INDEX `fk_peticion_estado1_idx` (`estado_noEstado` ASC) ,
  INDEX `fk_peticion_asesoria1_idx` (`asesoria_idasesoria` ASC) ,
  CONSTRAINT `fk_peticion_usuario1`
    FOREIGN KEY (`usuario_matricula`)
    REFERENCES `asesorapp`.`usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peticion_estado1`
    FOREIGN KEY (`estado_noEstado`)
    REFERENCES `asesorapp`.`estado` (`noEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peticion_asesoria1`
    FOREIGN KEY (`asesoria_idasesoria`)
    REFERENCES `asesorapp`.`asesoria` (`idasesoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `asesorapp`.`tipoCuenta`
-- -----------------------------------------------------
START TRANSACTION;
USE `asesorapp`;
INSERT INTO `asesorapp`.`tipoCuenta` (`tipo`, `cuenta`) VALUES (0, 'admin');
INSERT INTO `asesorapp`.`tipoCuenta` (`tipo`, `cuenta`) VALUES (1, 'alumno');
INSERT INTO `asesorapp`.`tipoCuenta` (`tipo`, `cuenta`) VALUES (2, 'profesor');

COMMIT;


-- -----------------------------------------------------
-- Data for table `asesorapp`.`estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `asesorapp`;
INSERT INTO `asesorapp`.`estado` (`noEstado`, `estado`) VALUES (0, 'Disponible');
INSERT INTO `asesorapp`.`estado` (`noEstado`, `estado`) VALUES (1, 'En solicitud');
INSERT INTO `asesorapp`.`estado` (`noEstado`, `estado`) VALUES (2, 'Ocupado');

COMMIT;

